### PR TITLE
fixing filter select hiding after click

### PR DESCRIPTION
**Pull request by gabrieldesar**
Fixing issue #38 as suggested by @JSinx

### CODE REVIEW

**Comment by faizaankhan** [comment]
Why is this not merged yet ??

**Comment by cle61** [comment]
sorry for the wait.

i will test the merge request this week end and make a new version for arctic_admin, normally

Important : please, do not changed the gemspec file.

**Comment by faizaankhan** [comment]
I think this UI should be merged with active admin :) Great Job

**Comment by cle61** [comment]
Thanks but there is still work !

**Pull request merged**
